version: '3.8'
services:
  python-env:
    container_name: python_env
    image: python:3.8-slim
    volumes:
      - .:/app
    working_dir: /app
    command: bash -c "pip install -r requirements_python-env.txt && /bin/bash"
    stdin_open: true
    tty: true
